[theme]
# Force light mode only
base="light"
primaryColor="#6366f1"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#262730"
font="sans serif"

[server]
# Mobile optimization
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
enableWebsocketCompression = true

[browser]
# Better mobile experience
gatherUsageStats = false
serverAddress = "0.0.0.0"